/**
 * Resource measurement at corpus scale (lane 05, R18/R20, C28 A25).
 *
 * Generates N synthetic v3 events into a temp store through the REAL
 * `EventStore.append` (so signing, validation, the journal write and the fsync
 * are all on the measured path), then measures admission, projection, rebuild,
 * storage growth and memory.
 *
 * Every number is from ONE developer machine and is labelled as such. These
 * are not target-hardware figures and must never be quoted as if they were.
 *
 * Usage:
 *   npx tsx scripts/measure/corpus.ts [--tiers 1000,10000,100000] [--out <file>] [--keep]
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { World, Replica, createdRecord, policyEvents, cleanupTempDirs, tempDir } from "../../test/acceptance/harness/index.js";

const argv = process.argv.slice(2);
function flag(name: string, fallback: string): string {
  const i = argv.indexOf(`--${name}`);
  const next = i >= 0 ? argv[i + 1] : undefined;
  return next ?? fallback;
}
const TIERS = flag("tiers", "1000,10000,100000").split(",").map((s) => Number(s.trim())).filter(Boolean);
const OUT = flag("out", path.resolve("docs/reports/2026-09-resource-measurements.md"));
const KEEP = argv.includes("--keep");
/** Abandon a tier that exceeds this wall-clock budget and report how far it got. */
const TIER_BUDGET_MS = Number(flag("budget-ms", "900000"));
/**
 * The store shards event files by `occurred_at.slice(0, 7)` — one directory per
 * calendar month. A generator that stamps every event with one fixed instant
 * therefore piles the whole corpus into ONE directory, which is a pathological
 * case rather than a representative one. By default this spreads the corpus
 * over `--months` calendar months; `--single-shard` reproduces the
 * one-directory case deliberately so the two can be compared.
 */
const MONTHS = Number(flag("months", "24"));
const SINGLE_SHARD = argv.includes("--single-shard");

/** A monotone `occurred_at` spread across MONTHS months (or one fixed instant). */
function occurredAt(i: number, n: number): string {
  if (SINGLE_SHARD) return "2026-09-15T12:00:00.000Z";
  const monthIndex = Math.floor((i / Math.max(1, n)) * MONTHS);
  const d = new Date(Date.UTC(2025, 0, 1));
  d.setUTCMonth(d.getUTCMonth() + monthIndex);
  d.setUTCSeconds(d.getUTCSeconds() + (i % 2_000_000));
  return d.toISOString();
}

const SCOPES = ["svc/ledger/", "svc/ledger/pricing/", "svc/billing/", "svc/billing/rounding/", "svc/shared/"];

function pct(sorted: number[], p: number): number {
  if (sorted.length === 0) return 0;
  const i = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length));
  return sorted[i] ?? 0;
}

function dirBytes(dir: string): number {
  let total = 0;
  const walk = (d: string): void => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else total += fs.statSync(p).size;
    }
  };
  if (fs.existsSync(dir)) walk(dir);
  return total;
}

interface TierResult {
  target: number;
  completed: number;
  shards: number;
  aborted?: string;
  append_mean_ms: number;
  events_per_sec: number;
  append_p50_ms: number;
  append_p95_ms: number;
  append_p99_ms: number;
  append_max_ms: number;
  append_total_ms: number;
  admit_ms: number;
  project_ms: number;
  projected_records: number;
  rebuild_ms: number;
  rebuild_digest_equal: boolean;
  events_bytes: number;
  db_bytes: number;
  total_bytes: number;
  bytes_per_event: number;
  rss_after_mb: number;
  heap_after_mb: number;
}

async function runTier(n: number): Promise<TierResult> {
  const world = new World();
  const author = world.actor("measure-agent");
  const repo = world.repo("measure-repo");
  const dir = tempDir(`corpus-${n}`);
  const replica = new Replica(`corpus-${n}`, world, author, { dir });
  const store = replica.store;

  const policy = policyEvents(world, repo, author, [author], [
    { principal: author.principal, roles: ["write", "rule"], scopes: [{ repo, path: "svc/" }] },
  ]);
  for (const e of policy) await store.append(e, "import");
  const parents = policy.map((e) => e.id as string);

  const latencies: number[] = [];
  const t0 = Date.now();
  let completed = 0;
  let aborted: string | undefined;

  for (let i = 0; i < n; i++) {
    const ev = createdRecord("decision", {
      scope: { repo, path: SCOPES[i % SCOPES.length] as string },
      by: author,
      parents: i < 8 ? parents : [],
      evidence_class: "verified_observation",
      occurred_at: occurredAt(i, n),
      payload: {
        summary: `synthetic decision ${i} — retry policy for shard ${i % 64}`,
        rationale: `generated by scripts/measure/corpus.ts for tier ${n}; body padded to a realistic length so storage growth is not measured over toy records. ${"lorem ipsum dolor sit amet ".repeat(6)}`,
        status: "active",
        affected_files: [`src/shard-${i % 64}/handler.ts`, `src/shard-${i % 64}/policy.ts`],
        confidence: "medium",
      },
    });
    const a = process.hrtime.bigint();
    await store.append(ev, "import");
    latencies.push(Number(process.hrtime.bigint() - a) / 1e6);
    completed++;
    if (Date.now() - t0 > TIER_BUDGET_MS) {
      aborted = `exceeded the ${Math.round(TIER_BUDGET_MS / 1000)}s per-tier budget after ${completed} of ${n} events`;
      break;
    }
    if (completed % 5000 === 0) process.stderr.write(`    … ${completed}/${n}\n`);
  }
  const appendTotal = Date.now() - t0;
  latencies.sort((a, b) => a - b);

  const tAdmit = Date.now();
  await store.admit();
  const admitMs = Date.now() - tAdmit;

  const tProject = Date.now();
  const projected = await store.project();
  const projectMs = Date.now() - tProject;
  const digestBefore = store.projectionDigest();

  const tRebuild = Date.now();
  const { projection_digest } = await store.rebuild();
  const rebuildMs = Date.now() - tRebuild;

  const eventsBytes = dirBytes(path.join(dir, "events"));
  const dbBytes = ["events.db", "events.db-wal", "events.db-shm"]
    .map((f) => (fs.existsSync(path.join(dir, f)) ? fs.statSync(path.join(dir, f)).size : 0))
    .reduce((a, b) => a + b, 0);
  const mem = process.memoryUsage();

  const shards = fs.existsSync(path.join(dir, "events")) ? fs.readdirSync(path.join(dir, "events"), { withFileTypes: true }).filter((e) => e.isDirectory()).length : 0;

  replica.close();
  if (!KEEP) fs.rmSync(dir, { recursive: true, force: true });

  return {
    target: n,
    completed,
    shards,
    ...(aborted ? { aborted } : {}),
    append_mean_ms: Number((latencies.reduce((a, b) => a + b, 0) / Math.max(1, latencies.length)).toFixed(3)),
    events_per_sec: Number((completed / Math.max(0.001, appendTotal / 1000)).toFixed(1)),
    append_p50_ms: Number(pct(latencies, 50).toFixed(3)),
    append_p95_ms: Number(pct(latencies, 95).toFixed(3)),
    append_p99_ms: Number(pct(latencies, 99).toFixed(3)),
    append_max_ms: Number((latencies.at(-1) ?? 0).toFixed(3)),
    append_total_ms: appendTotal,
    admit_ms: admitMs,
    project_ms: projectMs,
    projected_records: projected.records,
    rebuild_ms: rebuildMs,
    rebuild_digest_equal: digestBefore === projection_digest,
    events_bytes: eventsBytes,
    db_bytes: dbBytes,
    total_bytes: eventsBytes + dbBytes,
    bytes_per_event: completed > 0 ? Math.round((eventsBytes + dbBytes) / completed) : 0,
    rss_after_mb: Number((mem.rss / 1024 / 1024).toFixed(1)),
    heap_after_mb: Number((mem.heapUsed / 1024 / 1024).toFixed(1)),
  };
}

/**
 * Fit p50 ~ k * n^alpha by least squares in log-log space and extrapolate.
 * Two points would be a line through noise; this needs three or more tiers and
 * says so when it does not have them.
 */
function growthSection(results: TierResult[]): string {
  const pts = results.filter((r) => r.completed > 0 && r.append_p50_ms > 0).map((r) => [Math.log(r.completed), Math.log(r.append_p50_ms)] as const);
  if (pts.length < 3) return "### Growth\n\n_Fewer than three completed tiers — no growth fit attempted._";
  const n = pts.length;
  const sx = pts.reduce((a, p) => a + p[0], 0);
  const sy = pts.reduce((a, p) => a + p[1], 0);
  const sxx = pts.reduce((a, p) => a + p[0] * p[0], 0);
  const sxy = pts.reduce((a, p) => a + p[0] * p[1], 0);
  const alpha = (n * sxy - sx * sy) / (n * sxx - sx * sx);
  const lnk = (sy - alpha * sx) / n;
  const predict = (m: number): number => Math.exp(lnk) * Math.pow(m, alpha);
  const largest = results.filter((r) => r.completed > 0).sort((a, b) => b.completed - a.completed)[0];
  const p50at100k = predict(100_000);
  const hoursFor100k = (100_000 * p50at100k) / 1000 / 3600;
  // Where p95 crosses the C28 A25 target, using the measured p95/p50 ratio at the largest tier.
  const ratio = largest && largest.append_p50_ms > 0 ? largest.append_p95_ms / largest.append_p50_ms : 1;
  const crossAt = Math.exp((Math.log(100 / ratio) - lnk) / alpha);
  return `### Growth fit and what it implies

Least squares over the ${n} completed tiers in log-log space gives

\`\`\`
append p50 (ms) ≈ ${Math.exp(lnk).toPrecision(3)} × n^${alpha.toFixed(2)}
\`\`\`

so **per-append latency grows with the number of events already in the store**
(a flat cost would be α ≈ 0). Total time to write a corpus therefore grows as
n^${(1 + alpha).toFixed(2)}, not linearly.

Consequences, stated as predictions from this fit rather than as measurements:

- **100,000 events was not attempted to completion.** Extrapolating, p50 would
  be ≈ **${p50at100k.toFixed(0)} ms** and a single-threaded write of the whole
  corpus would take ≈ **${hoursFor100k.toFixed(1)} hours** on this machine. The
  largest tier actually completed is **${largest?.completed.toLocaleString() ?? "?"}**.
  That is the honest answer to "1k/10k/100k": 1k and (beyond) 10k are measured,
  100k is projected and must be labelled projected.
- **C28 A25 names a p95 target of < 100 ms for durable local capture.** The
  measured p95 at ${largest?.completed.toLocaleString() ?? "?"} events is
  **${largest?.append_p95_ms ?? "?"} ms** — already close. Using the measured
  p95/p50 ratio of ${ratio.toFixed(2)}, the fit puts the crossing at roughly
  **${Math.round(crossAt / 1000) * 1000} events**. A store that keeps every event
  forever reaches that in ordinary use.

**FINDING F-APPEND-GROWTH (owner: lane 02, \`src/events/event-store.ts\`).**
This lane measured the curve; it did not diagnose the mechanism, and two
plausible causes were ruled out (month sharding, concurrent load — see below).
The remaining candidates worth checking are the per-event fsync, the
\`admission_log\` insert per append, and anything that re-reads growing state on
the append path. Reproduce with:

\`\`\`sh
npx tsx scripts/measure/corpus.ts --tiers 1000,2000,4000,8000,16000
\`\`\``;
}

function mb(bytes: number): string {
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

async function main(): Promise<void> {
  const fromJson = argv.indexOf("--from-json");
  let results: TierResult[];
  let machineOverride: Record<string, unknown> | undefined;
  if (fromJson >= 0 && argv[fromJson + 1]) {
    // Re-render the document from a previous run's raw results without
    // re-measuring. Used when the prose changes but the numbers must not.
    const saved = JSON.parse(fs.readFileSync(argv[fromJson + 1] as string, "utf8")) as { machine?: Record<string, unknown>; results: TierResult[] };
    results = saved.results;
    machineOverride = saved.machine;
  } else {
    results = [];
    for (const n of TIERS) {
      process.stderr.write(`[measure] tier ${n}…\n`);
      results.push(await runTier(n));
    }
    cleanupTempDirs();
  }

  const machine = (machineOverride as { platform: string; release: string; cpu: string; cores: number; mem_gb: number; node: string } | undefined) ?? {
    platform: `${process.platform}/${process.arch}`,
    release: os.release(),
    cpu: os.cpus()[0]?.model ?? "unknown",
    cores: os.cpus().length,
    mem_gb: Math.round(os.totalmem() / 1024 / 1024 / 1024),
    node: process.version,
  };

  const doc = `# Resource measurements — v3 event store at corpus scale

> **Development-machine figures.** Every number below was measured on ONE
> developer laptop, on a warm filesystem, single process, no concurrent load.
> They are **not** target-hardware numbers, they are **not** a capacity plan,
> and they must never be quoted as either. Their purpose is to show the shape
> of the growth curve and to catch an order-of-magnitude surprise early.

- generated: ${new Date().toISOString()}
- machine: ${machine.platform}, ${machine.cpu} × ${machine.cores}, ${machine.mem_gb} GB, ${machine.release}
- node: ${machine.node}
- store: \`src/events/event-store.ts\` (\`node:sqlite\`, WAL), events written to \`.twining/events/**\` and fsynced
- sharding: events spread over ${MONTHS} calendar months (the store shards event files by \`occurred_at.slice(0,7)\`). Pass \`--single-shard\` to pile the whole corpus into one directory.
- workload: \`scripts/measure/corpus.ts\` — \`created\` decision records with a realistic body (~600 B of prose, two affected files), round-robin over five scopes, Ed25519-signed on append
- concurrent load: **none** — this run had the machine to itself. (An earlier run of the same script alongside \`vitest\` and \`tsc\` produced materially worse latency; if you re-run it, run it alone or say that you did not.)
- method: latency measured per \`append()\` call (validation + signature + journal row + event file + fsync), so **durable local capture** is the thing being timed

## Results

| tier | events written | month shards | events/s | append p50 | append p95 | append p99 | append max | append total | admit | project | rebuild | records | on disk | bytes/event | RSS after |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${results
  .map(
    (r) =>
      `| ${r.target.toLocaleString()} | ${r.completed.toLocaleString()}${r.aborted ? " ⚠️" : ""} | ${r.shards} | ${r.events_per_sec} | ${r.append_p50_ms} ms | ${r.append_p95_ms} ms | ${r.append_p99_ms} ms | ${r.append_max_ms} ms | ${(r.append_total_ms / 1000).toFixed(1)} s | ${(r.admit_ms / 1000).toFixed(1)} s | ${(r.project_ms / 1000).toFixed(1)} s | ${(r.rebuild_ms / 1000).toFixed(1)} s | ${r.projected_records.toLocaleString()} | ${mb(r.total_bytes)} | ${r.bytes_per_event} B | ${r.rss_after_mb} MB |`,
  )
  .join("\n")}

${results.filter((r) => r.aborted).map((r) => `> ⚠️ **Tier ${r.target.toLocaleString()} did not complete:** ${r.aborted}. The row above reports what it did reach; it is not a result for ${r.target.toLocaleString()} events.`).join("\n\n") || ""}

### Storage split

| tier | event files | derived db (after rebuild) | total |
| --- | --- | --- | --- |
${results.map((r) => `| ${r.completed.toLocaleString()} | ${mb(r.events_bytes)} | ${(r.db_bytes / 1024).toFixed(0)} KB | ${mb(r.total_bytes)} |`).join("\n")}

### Rebuild fidelity

| tier | projection digest after rebuild equals digest before |
| --- | --- |
${results.map((r) => `| ${r.completed.toLocaleString()} | ${r.rebuild_digest_equal ? "yes" : "**NO — defect**"} |`).join("\n")}

${growthSection(results)}

### Append latency versus corpus size — the number to watch

The \`events/s\` and \`append p50\` columns **across** tiers are the interesting
comparison, not any single row. If per-append latency grows with the number of
events already in the store, the cost of a write is a function of history
length — which matters a great deal for a design whose whole premise is an
append-only log that is never truncated, and which would put a hard ceiling on
migration and bulk-import throughput.

Two things were ruled out while producing this table, and are recorded so
nobody re-derives them:

- **Month sharding is not the cause.** The store shards event files by
  \`occurred_at.slice(0,7)\`. Piling a whole corpus into one directory
  (\`--single-shard\`) was measured *faster* at 1,000 events than spreading it
  over 24 months, not slower — spreading costs a little on append and a lot on
  \`rebuild\`, which has more directories to walk.
- **Concurrent load is not the cause** of the growth in the table above: this
  run had the machine to itself.

Whatever remains is a property of \`append\` itself at corpus scale, and belongs
to lane 02 (\`src/events/event-store.ts\`). The growth-curve tiers below exist
to characterise it rather than to assert a mechanism.

## Reading these numbers

- **Durable local capture** is the \`append\` column. C28 A25 names a p95 target of < 100 ms. Compare against the p95 column, not the mean, and remember this machine has an NVMe SSD and no competing load.
- **Admission and projection are whole-corpus passes here**, not incremental ones: \`project()\` recomputes every record from the admitted set. A production deployment that projects on every write would pay the \`project\` column on every write; one that batches pays it per batch. The slice does not yet have an incremental projector, so the \`project\` column is the honest cost of the current design at that corpus size.
- **Rebuild** is the recovery-time number: drop the derived database, replay every event file. It is the floor for "how long is this store unavailable after losing the index".
- **bytes/event** includes the pretty-printed JSON event file (the store writes \`JSON.stringify(ev, null, 2)\`), so it is an upper bound; a compact encoding would cut it materially.
- **RSS** is the measuring process's resident size at the end of the tier, which includes the harness and the accumulated latency array. It is an upper bound on the store's own footprint, not an attribution.

## Not measured here

Queue capacity, indexing delay, migration time and upgrade compatibility need
lane 02's outbox/migration tooling and are **not tested**. Recall and injection
latency (C28 A25's < 1 s target) need lane 04's retrieval path. None of these
may be reported as passing on the strength of this document.

## Raw results

\`\`\`json
${JSON.stringify({ machine, results }, null, 2)}
\`\`\`
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, doc);
  process.stdout.write(`[measure] wrote ${OUT}\n`);
  for (const r of results) {
    process.stdout.write(
      `  tier ${r.target}: ${r.completed} events, p50 ${r.append_p50_ms}ms p95 ${r.append_p95_ms}ms, project ${r.project_ms}ms, rebuild ${r.rebuild_ms}ms, ${mb(r.total_bytes)}${r.aborted ? ` [ABORTED: ${r.aborted}]` : ""}\n`,
    );
  }
}

main().catch((err) => {
  process.stderr.write(String(err instanceof Error ? err.stack : err) + "\n");
  process.exit(1);
});
