name: Bug Report
description: Report a bug in Twining MCP
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.
  - type: input
    id: version
    attributes:
      label: Twining version
      description: "Run `npm ls twining-mcp` or check package.json"
      placeholder: "e.g. 1.8.1"
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: "Run `node --version`"
      placeholder: "e.g. v20.11.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Configure MCP server with ...
        2. Call twining_post with ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      description: Paste any error messages or stack traces
      render: shell
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Twining is affected?
      options:
        - MCP Server
        - Dashboard
        - Claude Code Plugin
        - Storage / File I/O
        - Knowledge Graph
        - Context Assembly
        - Other
    validations:
      required: true
