/**
 * DP4 — the declared token estimator (oracle C26 A01–A04).
 *
 * ## What a budget has to mean
 *
 * `max_tokens: 4000` has to be a bound the emitted payload cannot cross. The
 * 2.x estimator (`src/utils/tokens.ts`, `ceil(chars/4)`) is a *central*
 * estimate: it is wrong in both directions, and it undercounts on exactly the
 * content that matters — JSON punctuation, escaped strings, code, CJK, emoji.
 * A bound that undercounts is not a bound.
 *
 * So this estimator is **conservative by construction**: for every input it
 * returns a value greater than or equal to the true token count of any
 * byte-level BPE tokenizer whose vocabulary contains all 256 single bytes.
 * Every production tokenizer in this class (cl100k, o200k, Claude's) qualifies.
 *
 * ## The bound, and why it is what it is
 *
 * In such a tokenizer every token decodes to at least one byte, so
 *
 *     tokens(s) <= utf8_byte_length(s)
 *
 * and that inequality is tight (a string of bytes with no merges costs one
 * token per byte). This is a *proof*, not a measurement — it cannot undercount
 * and it needs no vocabulary, no network and no model file.
 *
 * It is also loose: real English prose runs about 4 bytes/token, so the proven
 * bound charges ~4x. That cost is deliberate and is the conservative default
 * my brief asks for. The calibration machinery below exists so the bound can
 * be *tightened with evidence* rather than with a guess:
 *
 *  - `TABLES.proven` — ratios that are mathematically 1 token per byte. Shipped
 *    as the default. Provenance `proven-upper-bound`. Never undercounts.
 *  - `TABLES.measured` — per-class max ratios MEASURED against a named
 *    reference tokenizer over a named corpus, times a safety factor. Generated
 *    by `scripts/calibrate-tokenizer.mjs`, which needs a real tokenizer and is
 *    therefore not run in tests.
 *
 * ## The shipped table (`ACTIVE_TABLE`)
 *
 * `calibration.json` sits next to this module and is imported statically, so it
 * travels wherever the module travels: `tsc` copies it into `dist/retrieval/`
 * and esbuild inlines it into the plugin bundle. There is no runtime file read
 * and no path resolution to get wrong.
 *
 * It is still VALIDATED at module load, because a committed artefact can be
 * hand-edited, merged badly, or regenerated by a future script with a different
 * shape. `validateCalibrationTable` rejects anything that is not a complete
 * measured table whose every ratio lies in `(0, proven]` and whose corpus names
 * a sha256; on rejection `ACTIVE_TABLE` is `PROVEN_TABLE` and every estimate
 * says `provenance: "proven-upper-bound"`. A calibration file can therefore
 * only ever TIGHTEN the bound, never loosen or break it.
 *
 * `conservative_fallback` stays `true` either way. A measured table is an
 * empirical bound over a named corpus, not a count: text unlike the corpus can
 * exceed it, so the flag keeps meaning "this is a bound, ask `countExact` if
 * you need the number".
 *
 * ## Where the safety factor is applied
 *
 * ONCE, into the ratios, by whoever builds the table (`buildCalibrationTable`
 * and `scripts/calibrate-tokenizer.mjs` both do it before clamping). `ratios`
 * is therefore the final tokens-per-byte charge and `estimate` multiplies by
 * nothing else; `safety_factor` survives as provenance — it says how the
 * ratios were derived, not what to do with them. Applying it again at estimate
 * time would have charged 1.15x twice on the first real table.
 *
 * ## Exact mode
 *
 * `countExact` calls the Anthropic count-tokens API, and ONLY when
 * `ANTHROPIC_API_KEY` is set and `allow_network` is passed. It is never
 * reached from a test: `estimate()` is pure and synchronous.
 */

import calibrationJson from "./calibration.json" with { type: "json" };

export const TOKENIZER_NAME = "twining-conservative-utf8";
export const TOKENIZER_VERSION = "1.0.0";
export const TOKENIZER_ID = `${TOKENIZER_NAME}/${TOKENIZER_VERSION}`;

/**
 * Character classes the calibration table is keyed on. Splitting the text this
 * way is what lets a calibrated table be tighter than a single global ratio:
 * ASCII prose compresses far better than punctuation or CJK, and a single
 * average would have to be pinned to the worst class.
 */
export type CharClass = "ascii_alnum" | "ascii_space" | "ascii_punct" | "latin1_supp" | "multibyte";

export interface CalibrationTable {
  /** Table identity, recorded in every receipt. */
  id: string;
  /** How the ratios were obtained. A reader must be able to tell. */
  provenance: "proven-upper-bound" | "measured";
  /** The reference tokenizer the ratios were measured against, when measured. */
  reference?: string;
  /** The corpus the ratios were measured over, when measured. */
  corpus?: {
    name: string;
    documents: number;
    bytes: number;
    sha256: string;
    /** Corpus documents the reference tokenizer refused (blank/whitespace-only). */
    skipped_blank?: string[];
  };
  /**
   * The multiplier that was ALREADY APPLIED to the measured max ratios below.
   * Provenance, not an instruction: `estimate` does not re-apply it. 1 for a
   * proven table.
   */
  safety_factor: number;
  /**
   * Upper bound on tokens per UTF-8 BYTE of text in this class, safety factor
   * included. This is the number an estimate charges, unmodified.
   */
  ratios: Record<CharClass, number>;
  /**
   * Tokens charged for the payload as a whole, independent of content: BOS/EOS
   * and any wrapper the transport adds. Conservative constant, never zero.
   */
  envelope_overhead_tokens: number;
}

/**
 * The shipped default.
 *
 * Every ratio is 1.0 tokens per byte, which is the proven bound. Nothing here
 * was measured, and the `provenance` field says so.
 */
export const PROVEN_TABLE: CalibrationTable = {
  id: "proven-utf8-bytes/1",
  provenance: "proven-upper-bound",
  safety_factor: 1,
  ratios: {
    ascii_alnum: 1,
    ascii_space: 1,
    ascii_punct: 1,
    latin1_supp: 1,
    multibyte: 1,
  },
  // A byte-level BPE adds at most a handful of control tokens around a
  // message. 8 is comfortably above every published value and costs nothing.
  envelope_overhead_tokens: 8,
};

/** Every class a complete table must price. Order is irrelevant; presence is not. */
export const CHAR_CLASSES: readonly CharClass[] = [
  "ascii_alnum",
  "ascii_space",
  "ascii_punct",
  "latin1_supp",
  "multibyte",
] as const;

function isFinitePositive(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v) && v > 0;
}

/**
 * Accept a calibration artefact only if it is a COMPLETE measured table that
 * can only tighten the bound. Returns `null` — never throws, never repairs —
 * so a bad file degrades to the proof instead of taking the process down.
 *
 * The rules, and why each one is here:
 *
 *  - `provenance: "measured"`. A file claiming `proven-upper-bound` is either a
 *    copy of the constant (pointless) or a lie about ratios below 1.
 *  - every class in `CHAR_CLASSES` priced, each ratio in `(0, proven]`. Above
 *    the proven ratio the "bound" would undercount, which is the one failure
 *    this module exists to prevent; at or below zero it would charge nothing
 *    for real bytes. A partial table is rejected rather than back-filled,
 *    because a silently proven-filled class looks measured in the receipt.
 *  - `safety_factor >= 1`. Below 1 the ratios were shrunk BELOW what was
 *    measured, which is a margin pointing the wrong way.
 *  - a corpus with a name, a positive document count, positive bytes and a
 *    sha256. Without the hash the claim "measured" is unfalsifiable: nobody can
 *    tell which text produced these numbers.
 *
 * `envelope_overhead_tokens` is clamped UP to the proven envelope rather than
 * rejected, matching `buildCalibrationTable`: the envelope is a constant of the
 * transport, not something the corpus measured.
 */
export function validateCalibrationTable(raw: unknown): CalibrationTable | null {
  if (typeof raw !== "object" || raw === null) return null;
  const t = raw as Record<string, unknown>;

  if (typeof t.id !== "string" || t.id.trim() === "") return null;
  if (t.provenance !== "measured") return null;
  if (t.reference !== undefined && (typeof t.reference !== "string" || t.reference.trim() === "")) return null;
  if (!isFinitePositive(t.safety_factor) || t.safety_factor < 1) return null;

  const corpus = t.corpus;
  if (typeof corpus !== "object" || corpus === null) return null;
  const c = corpus as Record<string, unknown>;
  if (typeof c.name !== "string" || c.name.trim() === "") return null;
  if (!isFinitePositive(c.documents)) return null;
  if (!isFinitePositive(c.bytes)) return null;
  if (typeof c.sha256 !== "string" || c.sha256.trim() === "") return null;
  if (c.skipped_blank !== undefined && !(Array.isArray(c.skipped_blank) && c.skipped_blank.every((x) => typeof x === "string"))) {
    return null;
  }

  const rawRatios = t.ratios;
  if (typeof rawRatios !== "object" || rawRatios === null) return null;
  const rr = rawRatios as Record<string, unknown>;
  const ratios = {} as Record<CharClass, number>;
  for (const cls of CHAR_CLASSES) {
    const value = rr[cls];
    if (!isFinitePositive(value)) return null;
    if (value > PROVEN_TABLE.ratios[cls]) return null;
    ratios[cls] = value;
  }

  const envelope = t.envelope_overhead_tokens;
  if (typeof envelope !== "number" || !Number.isFinite(envelope) || envelope < 0) return null;

  return {
    id: t.id,
    provenance: "measured",
    ...(typeof t.reference === "string" ? { reference: t.reference } : {}),
    corpus: {
      name: c.name,
      documents: c.documents,
      bytes: c.bytes,
      sha256: c.sha256,
      ...(c.skipped_blank ? { skipped_blank: c.skipped_blank as string[] } : {}),
    },
    safety_factor: t.safety_factor,
    ratios,
    envelope_overhead_tokens: Math.max(envelope, PROVEN_TABLE.envelope_overhead_tokens),
  };
}

/** The validated table, or the proof. Never throws; never returns undefined. */
export function loadCalibrationTable(raw: unknown): CalibrationTable {
  return validateCalibrationTable(raw) ?? PROVEN_TABLE;
}

/**
 * The table every default estimate uses.
 *
 * `calibration.json` when it validates, `PROVEN_TABLE` when it does not (or
 * when a build strips it). Read `ACTIVE_TABLE.provenance` — not the fact that a
 * file exists — to know which one is in force.
 */
export const ACTIVE_TABLE: CalibrationTable = loadCalibrationTable(calibrationJson as unknown);

export const TABLES: Record<string, CalibrationTable> = {
  proven: PROVEN_TABLE,
  active: ACTIVE_TABLE,
  ...(ACTIVE_TABLE.provenance === "measured" ? { measured: ACTIVE_TABLE } : {}),
};

/** Bytes per class. Exported so the calibration harness measures the same split. */
export function classifyBytes(text: string): Record<CharClass, number> {
  const out: Record<CharClass, number> = {
    ascii_alnum: 0,
    ascii_space: 0,
    ascii_punct: 0,
    latin1_supp: 0,
    multibyte: 0,
  };
  for (const ch of text) {
    const cp = ch.codePointAt(0) as number;
    const bytes = Buffer.byteLength(ch, "utf8");
    if (cp < 0x80) {
      if ((cp >= 48 && cp <= 57) || (cp >= 65 && cp <= 90) || (cp >= 97 && cp <= 122)) out.ascii_alnum += bytes;
      else if (cp === 32 || cp === 9 || cp === 10 || cp === 13) out.ascii_space += bytes;
      else out.ascii_punct += bytes;
    } else if (cp < 0x100) {
      out.latin1_supp += bytes;
    } else {
      out.multibyte += bytes;
    }
  }
  return out;
}

/**
 * What the table behind an estimate declares about itself.
 *
 * Carried on every estimate so a receipt can be read years later without the
 * table: `measured` says which corpus and which safety factor produced the
 * ratios, `proven-upper-bound` says nothing was measured at all.
 */
export interface DeclaredTable {
  table_id: string;
  provenance: CalibrationTable["provenance"];
  /** Already folded into the ratios. Recorded so the derivation is legible. */
  safety_factor: number;
  envelope_overhead_tokens: number;
  reference?: string;
  corpus?: CalibrationTable["corpus"];
}

/** The self-description a table hands to every estimate it prices. */
export function describeTable(table: CalibrationTable): DeclaredTable {
  return {
    table_id: table.id,
    provenance: table.provenance,
    safety_factor: table.safety_factor,
    envelope_overhead_tokens: table.envelope_overhead_tokens,
    ...(table.reference !== undefined ? { reference: table.reference } : {}),
    ...(table.corpus !== undefined ? { corpus: table.corpus } : {}),
  };
}

export interface Estimate {
  tokens: number;
  tokenizer_id: string;
  table_id: string;
  /**
   * True whenever the value is a bound rather than a measured count — which is
   * ALWAYS, for both table kinds. The proven table is a proof; a measured table
   * is an empirical bound over a named corpus and text unlike that corpus can
   * exceed it. `countExact` is the only thing that returns false here.
   */
  conservative_fallback: boolean;
  bytes: number;
  /** Provenance of the table that priced this estimate. */
  declared: DeclaredTable;
}

/**
 * The conservative bound. Pure, synchronous, no network, no model.
 *
 * `Math.ceil` per class rather than on the sum: rounding each class up
 * separately can only raise the total, and raising is the safe direction.
 *
 * `table.ratios` is charged as-is. The safety factor is already inside it (see
 * the header); multiplying again here would apply the margin twice.
 */
export function estimate(text: string, table: CalibrationTable = ACTIVE_TABLE): Estimate {
  const classes = classifyBytes(text);
  let tokens = table.envelope_overhead_tokens;
  for (const [cls, bytes] of Object.entries(classes) as Array<[CharClass, number]>) {
    if (bytes === 0) continue;
    tokens += Math.ceil(bytes * table.ratios[cls]);
  }
  return {
    tokens,
    tokenizer_id: TOKENIZER_ID,
    table_id: table.id,
    conservative_fallback: true,
    bytes: Buffer.byteLength(text, "utf8"),
    declared: describeTable(table),
  };
}

/** Bare number, for the hot path inside the packet builder. */
export function estimateTokensConservative(text: string, table: CalibrationTable = ACTIVE_TABLE): number {
  return estimate(text, table).tokens;
}

/**
 * Exact count via the Anthropic count-tokens API.
 *
 * Refuses unless `allow_network` is explicitly passed AND `ANTHROPIC_API_KEY`
 * is set, so a test can never reach the network by forgetting a flag. Returns
 * `null` rather than throwing when unavailable — an exact count is an
 * optimisation, never a correctness dependency.
 */
export async function countExact(
  text: string,
  opts: { allow_network: boolean; model?: string } = { allow_network: false },
): Promise<{ tokens: number; tokenizer_id: string; conservative_fallback: false } | null> {
  if (!opts.allow_network) return null;
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  /* c8 ignore start — network path, never exercised in tests */
  try {
    const mod = (await import("@anthropic-ai/sdk")) as unknown as {
      default: new (o: { apiKey: string }) => {
        messages: { countTokens: (b: unknown) => Promise<{ input_tokens: number }> };
      };
    };
    const client = new mod.default({ apiKey: key });
    const model = opts.model ?? "claude-sonnet-4-5";
    const res = await client.messages.countTokens({
      model,
      messages: [{ role: "user", content: text }],
    });
    return { tokens: res.input_tokens, tokenizer_id: `anthropic-count-tokens/${model}`, conservative_fallback: false };
  } catch {
    return null;
  }
  /* c8 ignore stop */
}

/**
 * Build a calibration table from measured (reference, text) pairs.
 *
 * Exported so the harness and its test share one implementation. The ratio for
 * a class is the maximum over the corpus of `tokens / bytes` for documents
 * dominated by that class, times the safety factor — a max, never a mean,
 * because a mean undercounts half the corpus by construction.
 *
 * The safety factor is applied HERE, before the clamp, so `ratios` leaves this
 * function as the final charge — matching what `scripts/calibrate-tokenizer.mjs`
 * writes into `calibration.json`, and matching what `estimate` charges. One
 * place applies the margin; nobody applies it twice.
 *
 * Any resulting ratio is clamped to the proven bound: a measurement can only
 * ever make the estimate TIGHTER, never looser than the proof allows.
 */
export function buildCalibrationTable(opts: {
  id: string;
  reference: string;
  corpus: { name: string; documents: number; bytes: number; sha256: string };
  safety_factor: number;
  /** Per-class observed maximum of tokens/byte. */
  observed_max: Partial<Record<CharClass, number>>;
  envelope_overhead_tokens: number;
}): CalibrationTable {
  const ratios = {} as Record<CharClass, number>;
  for (const cls of CHAR_CLASSES) {
    const observed = opts.observed_max[cls];
    const proven = PROVEN_TABLE.ratios[cls];
    ratios[cls] = observed === undefined ? proven : Math.min(proven, observed * opts.safety_factor);
  }
  return {
    id: opts.id,
    provenance: "measured",
    reference: opts.reference,
    corpus: opts.corpus,
    safety_factor: opts.safety_factor,
    ratios,
    envelope_overhead_tokens: Math.max(opts.envelope_overhead_tokens, PROVEN_TABLE.envelope_overhead_tokens),
  };
}
