/**
 * MCP tool handlers for housekeeping — periodic store maintenance and
 * stale-item archival. Both tools are dry-run by default.
 */
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { HousekeepingEngine } from "../engine/housekeeping.js";
import type { BlackboardEngine } from "../engine/blackboard.js";
import { formatBytes } from "../engine/archive-compactor.js";
import { toolResult, toolError } from "../utils/errors.js";
import type { IDecisionStore } from "../storage/interfaces.js";

export function registerHousekeepingTools(
  server: McpServer,
  housekeepingEngine: HousekeepingEngine,
  blackboardEngine: BlackboardEngine,
  decisionStore: IDecisionStore,
): void {
  server.registerTool(
    "twining_housekeeping",
    {
      description:
        "Run periodic maintenance on Twining stores. Preview by default (dry run); preview simulates the full pass pipeline, so its counts match what execute will do on the same state (#39). " +
        "Archives old entries (keeping decisions and unresolved need/warning entries, #40), removes duplicates, surfaces stale decisions and dangling warnings, " +
        "prunes orphaned graph entities, rotates old metrics, and backfills missing superseded_by back-links on superseded decisions. " +
        "Pass staleness_review: true to also flag entries whose scope/files/branch are gone. " +
        "Pass execute: true to apply changes.",
      inputSchema: {
        execute: z
          .boolean()
          .optional()
          .describe("Set to true to apply changes. Default is false (preview only)."),
        promote_provisionals: z
          .boolean()
          .optional()
          .describe("Set to true to auto-promote stale provisional decisions to active. Default is false (report only)."),
        staleness_review: z
          .boolean()
          .optional()
          .describe(
            "Set to true to scan blackboard entries and decisions for staleness — flags items whose scope path, affected files, or originating branch no longer exist. Returns candidates only; use twining_archive_stale to act on them.",
          ),
        merge_sweep: z
          .boolean()
          .optional()
          .describe(
            "Set to true to detect branches deleted since the last housekeeping run (typically post-merge cleanup) and flag entries provenance-stamped with those branches. First call records the initial branch snapshot and returns no candidates. The branch snapshot is advanced only when execute=true; preview passes leave the baseline untouched so deletions stay visible across multiple previews. Returns candidates only; use twining_archive_stale to act on them. When run alongside staleness_review, branch-gone duplicates are removed from staleness_review (merge_sweep is the more specific signal).",
          ),
        compact_archives: z
          .boolean()
          .optional()
          .describe(
            "Set to true to scan .twining/archive/*.jsonl for junk generated by the pre-1.24.0 auto-archive feedback loop ('Archive: N entries archived' summary findings, #35) and report how much is reclaimable. With execute: true, junk lines are dropped (streaming, atomic rewrite), archive files left empty are deleted, and an audit-trail finding is posted. Only entries matching the archiver's exact signature are dropped — everything else, including unparseable lines, is preserved.",
          ),
        stale_days: z
          .number()
          .optional()
          .describe("Flag provisional decisions older than this many days (default: 7)"),
        metrics_retention_days: z
          .number()
          .optional()
          .describe("Remove metrics older than this many days (default: 30)"),
      },
    },
    async (args) => {
      try {
        const result = await housekeepingEngine.run({
          execute: args.execute,
          promote_provisionals: args.promote_provisionals,
          staleness_review: args.staleness_review,
          merge_sweep: args.merge_sweep,
          compact_archives: args.compact_archives,
          stale_days: args.stale_days,
          metrics_retention_days: args.metrics_retention_days,
        });

        // Audit trail for archive compaction (mirrors twining_archive_stale):
        // when junk was actually dropped, post a finding recording what and
        // how much. _skipAutoArchive so the audit post can never re-arm the
        // very loop this pass repairs.
        const ac = result.archive_compaction;
        if (args.execute && ac && ac.total_junk > 0) {
          const touched = ac.files.filter((f) => f.junk_count > 0);
          await blackboardEngine.post({
            entry_type: "finding",
            summary: `Archive compaction: dropped ${ac.total_junk} loop-junk entries from ${touched.length} archive file(s), reclaimed ~${formatBytes(ac.total_bytes_reclaimable)}`,
            detail: [
              "Repair pass for the pre-1.24.0 auto-archive feedback loop (#35).",
              `Dropped ${ac.total_junk} archiver-generated summary findings ("Archive: N entries archived"); ${ac.total_survivors} entries preserved; ${ac.files_deleted} emptied file(s) deleted.`,
              ...touched.map(
                (f) =>
                  `${f.file}: dropped ${f.junk_count}, kept ${f.survivor_count}${f.deleted ? ", file deleted" : ""}`,
              ),
            ].join("\n"),
            tags: ["housekeeping", "archive-compaction"],
            scope: "project",
            _skipAutoArchive: true,
          });
        }

        return toolResult(result);
      } catch (e) {
        return toolError(
          e instanceof Error ? e.message : "Unknown error",
          "INTERNAL_ERROR",
        );
      }
    },
  );

  server.registerTool(
    "twining_archive_stale",
    {
      description:
        "Archive a list of stale items by ID — typically the candidate IDs returned by twining_housekeeping with staleness_review: true. Decisions move to status \"archived\" (excluded from assemble/why). Blackboard entries are dismissed. Items remain on disk with provenance preserved.",
      inputSchema: {
        ids: z
          .array(z.string())
          .min(1)
          .describe("IDs to archive (mix of decision and blackboard IDs)"),
        reason: z
          .string()
          .optional()
          .describe("Optional rationale for the archive — recorded as a finding for the audit trail"),
        reasons: z
          .record(z.string(), z.string())
          .optional()
          .describe(
            "Optional per-item rationale keyed by ID — recorded per item in the audit-trail finding so a future reviewer can spot bad calls (#16, semantic review)",
          ),
      },
    },
    async (args) => {
      try {
        const archivedDecisions: string[] = [];
        const archivedEntries: string[] = [];
        const notFound: string[] = [];

        // Pull the decision index once so we can decide kind without N round-trips.
        const decisionIndex = await decisionStore.getIndex();
        const decisionIds = new Set(decisionIndex.map((e) => e.id));

        const blackboardIds: string[] = [];
        for (const id of args.ids) {
          if (decisionIds.has(id)) {
            try {
              await decisionStore.updateStatus(id, "archived");
              archivedDecisions.push(id);
            } catch {
              notFound.push(id);
            }
          } else {
            blackboardIds.push(id);
          }
        }

        if (blackboardIds.length > 0) {
          const dismissed = await blackboardEngine.dismiss(blackboardIds);
          archivedEntries.push(...dismissed.dismissed);
          notFound.push(...dismissed.not_found);
        }

        if (archivedDecisions.length + archivedEntries.length > 0) {
          const perItemReasons = Object.entries(args.reasons ?? {})
            .filter(([id]) =>
              archivedDecisions.includes(id) || archivedEntries.includes(id),
            )
            .map(([id, why]) => `  ${id}: ${why}`);
          await blackboardEngine.post({
            entry_type: "finding",
            summary: `Archived ${archivedDecisions.length + archivedEntries.length} stale items via housekeeping`,
            detail: [
              args.reason ? `Reason: ${args.reason}` : null,
              archivedDecisions.length > 0 ? `Decisions: ${archivedDecisions.join(", ")}` : null,
              archivedEntries.length > 0 ? `Blackboard entries: ${archivedEntries.join(", ")}` : null,
              perItemReasons.length > 0
                ? `Per-item reasons:\n${perItemReasons.join("\n")}`
                : null,
            ]
              .filter(Boolean)
              .join("\n"),
            tags: ["housekeeping", "stale-archive"],
            scope: "project",
          });
        }

        return toolResult({
          archived_decisions: archivedDecisions,
          archived_entries: archivedEntries,
          not_found: notFound,
          total_archived: archivedDecisions.length + archivedEntries.length,
        });
      } catch (e) {
        return toolError(
          e instanceof Error ? e.message : "Unknown error",
          "INTERNAL_ERROR",
        );
      }
    },
  );
}
